version: '3.6'
services:
  app:
    image: padoca-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=/app
    command: streamlit run pages/01_excel.py
    ports:
      - "9001:9001"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
